services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    develop:
      watch:
        - action: sync
          path: ./client
          target: /usr/src/client
        - action: rebuild
          path: ./client/package.json
