version: "2.39.1"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    restart: always
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /usr/src/client/src
        - action: rebuild
          path: ./client/package.json
